### ISSUE TITLE
Weird result using pytz and Python 3.6

### ISSUE THREAD

**Issue by David-Guillot** [adamchainz/time-machine#105]
Hi there,

First of all thank you for this excellent lib, and let me say that the issue I'm reporting here has been worked around already, thanks to `time-machine`'s ability to accept dates as strings. I just want to ask you if this is something you'd like to address.

### Context
* Python 3.6.12
* pytz 2020.5
* time-machine 2.0.1

### Issue
```python
In [4]: from datetime import datetime
   ...: 
   ...: import pytz
   ...: import time_machine
   ...: 
   ...: tz_paris = pytz.timezone('Europe/Paris')
   ...: 
   ...: @time_machine.travel(datetime(2021, 1, 28, 0, 1, 0, tzinfo=tz_paris))
   ...: def test():
   ...:     print(datetime.now(tz=tz_paris))
   ...: 
   ...: test()
2021-01-28 00:52:00+01:00
```
(and yes, it's repeatable, always `00:52` instead of `00:01` :zany_face: )

It seems that the issue is specific to the combination of `pytz` and `time_machine`, because:

### Workaround

```python
In [6]: from datetime import datetime
   ...: 
   ...: import pytz
   ...: import time_machine
   ...: 
   ...: tz_paris = pytz.timezone('Europe/Paris')
   ...: 
   ...: @time_machine.travel('2021-01-28T00:01:00CET')
   ...: def test():
   ...:     print(datetime.now(tz=tz_paris))
   ...: 
   ...: test()
2021-01-28 00:01:00+01:00
```
### Question

What do you think? I see in the `README` that you recommend using `zoneinfo` (or its backport if python<3.8), but my code already relies on `pytz`: do you consider my code should change to stop relying on `pytz`, or `pytz` should change, or `time-machine` should change?

Thanks,

**Comment by adamchainz** [comment]
You should stop using pytz because it doesn't handle all the edge cases around datetime transitions and ambiguous datetimes correctly that's the main reason for zoneinfo existing in the standard library. See the relevant PEP's. For example, we're working to move Django from pytz to zoneinfo, with the author of zoneinfo, Paul Ganssle.

Can you try your example with zoneinfo?

**Comment by David-Guillot** [comment]
With `zoneinfo` backport for Python 3.6:

```python
In [2]: from datetime import datetime
   ...: 
   ...: from backports.zoneinfo import ZoneInfo
   ...: import time_machine
   ...: 
   ...: tz_paris = ZoneInfo('Europe/Paris')
   ...: 
   ...: @time_machine.travel(datetime(2021, 1, 28, 0, 1, 0, tzinfo=tz_paris))
   ...: def test():
   ...:     print(datetime.now(tz=tz_paris))
   ...: test()
2021-01-28 00:01:00+01:00
```

Thank you for your quick and clear answer, we'll start moving from `pytz` to `zoneinfo`.

**Comment by adamchainz** [comment]
FYI more info on Paul's blog, starting with this post: https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html
