### ISSUE TITLE
Type hints (PEP 484)

### ISSUE THREAD

**Issue by JoseKilo** [adamchainz/time-machine#148]
Hi, great library.

Any plans to add type hints ?

At the moment I'm having to use

```
[mypy-time_machine.*]
ignore_missing_imports = True
```

**Comment by adamchainz** [comment]
Released in 2.2.0 - try that out!

**Comment by JoseKilo** [comment]
> Released in 2.2.0 - try that out!

Amazing ! working as expected for my use cases. Thanks a lot :raised_hands:

**Comment by adamchainz** [comment]
Great to hear! I just wrote a blog post on recent updates to time-machine: https://adamj.eu/tech/2021/07/05/recent-updates-to-time-machine/
