### ISSUE TITLE
Freeze time instead of just shifting it

### ISSUE THREAD

**Issue by jaraqueffdc** [adamchainz/time-machine#151]
Hi! This library looks very cool, even more with the added support for pytest. I have a question which might be more related with me not understanding the use cases or purpose than the tool itself.

I thought I would be able to tell the library: everytime I call now I want you to return this. Instead what I found is that when I call the `move_to` method in the time_machine fixture, time goes back to that time but the starts moving forward accurately. What I wanted to be able to do is to always get the same value when utcnow is called so I can test the value of queries that I am generating on the fly.

Is this possible? Thanks!

**Comment by adamchainz** [comment]
To freeze time, use `tick=False`. I've realized this isn't exposed to the pytest fixture right now, so I've made #152 to solve this, which will be released shortly.

**Comment by adamchainz** [comment]
Check it out in 2.3.0!

**Comment by jaraqueffdc** [comment]
Thanks! The workaround I had was to make my own fixture with travel which allows tick. Thanks for the quick reply!
