### ISSUE TITLE
Consider removing warning temporarily when traveling in time

### ISSUE THREAD

**Issue by gjeusel** [adamchainz/time-machine#164]
I just came across one case:

```
  <...>/lib/python3.9/site-packages/urllib3/connection.py:379: SystemTimeWarning: System time is way off (before 2020-07-01). This will probably lead to SSL verification errors
```

I've set the ignore warning manually, but it would be nice if time_machine could handle it !

```python
import warnings
from urllib3.exceptions import SystemTimeWarning

warnings.filterwarnings(
    action="ignore", category=SystemTimeWarning, module="urllib3"
)
```

**Comment by adamchainz** [comment]
I don't think time-machine should interfere with security level warnings.

I would recommend avoiding making HTTP requests whilst time travelling. It really can go wrong with certificate validities etc. Perhaps you want to avoid making requests in your tests by using [requests-mock](https://requests-mock.readthedocs.io/en/latest/) ?
