### ISSUE TITLE
Tests fail when test suite is run west of UTC

### ISSUE THREAD

**Issue by pganssle** [adamchainz/time-machine#181]
### Python Version

3.9.7

### pytest Version

6.2.5

### Package Version

main

### Description

Several of the tests in the test suite, notably `test_time_localtime`, `test_strftime_no_args` and `test_date_today` are broken when run on a machine with its time zone set west of UTC.

You can verify this by adding `passenv=TZ` to the `tox.ini` file (in the `[testenv]` section) and running `TZ=America/New_York tox -e py39`, or by looking at the github actions on #180, which is a PR to start running the tests under different time zones as part of the CI.

The problem is that these tests all assume that `time.localtime()` will return a 1970-01-01 time when `time_machine` has travelled to `EPOCH`, but this is not right — the Unix epoch is `1970-01-01T00:00Z`, which in New York is `1969-12-31T19:00:00-05:00`.

I'm thinking that the right solution is to relax that assumption for the tests.

As a side note: if you relax this assumption, you'll likely be testing some *general property* of these functions rather than a known value (e.g. "`time.localtime()` gives the same thing as `time.localtime(0)`"), in which case it may make sense to actually use `hypothesis` and test the property more generally, not just at the point of the epoch.

**Comment by adamchainz** [comment]
Thanks for the report Paul.

Rather than double up on the CI runtime and complicate the tests, I came up with a different solution in #183. This PR isolates the tests from the OS timezone by setting `TZ` and using `tzset()` at the start. Not sure about a Windows way of adding the isolation, but the test suite is already incompatible with Windows.

I'm aware of property testing but I don't think it's required here.

**Comment by pganssle** [comment]
> Rather than double up on the CI runtime and complicate the tests, I came up with a different solution in #183. This PR isolates the tests from the OS timezone by setting `TZ` and using `tzset()` at the start. Not sure about a Windows way of adding the isolation, but the test suite is already incompatible with Windows.

I'll note that this doesn't quite double the CI runtime, I only added two new CI targets — I think "works on the latest Python in a different time zone" is good enough, so really it only adds 2 additional CI jobs.

As to the solution of basically forcing `TZ=UTC`, I'm not a big fan because I think that the project _itself_ should work when run on a time zone that is not UTC. This is actually a problem with `freeezgun` — their test suite also fails when run not on UTC, but they also seem to make fundamental assumptions that you are running your tests in UTC. It's actually one of the reasons I was hoping to switch some test suites from `freezegun` to `time-machine` in the first place.

I think you should actively support running these tests in non-UTC zones, and that non-UTC zones should be part of the test matrix.

I am also not a huge fan of changing the time zone during a run of the Python program. `tzset` only gets you so far, and things like `dateutil.tz.tzlocal` will not really work properly when you do that (not that that applies here, but in general it's not as safe as you might think it is). If you don't want to use some sort of property-based tests (which I'll note you were already doing, it was just that the property had an assumption that the tz offset was in `[0, 24)`), you'd probably be better off using a `pytest.mark.skip` decorator that skips tests not run when the time zone is set to UTC.
