### ISSUE TITLE
Complete copying freezegun API

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/time-machine#20]
* [x] `.tick()` method
* [x] `.move_to()` method
* [ ] `auto_tick_seconds`(?) - #14 
* [ ] Wrapping non-TestCase classes like pytest classes. Probably adopt the unittest mechanism where only callables starting `test_` (or a configurable prefix) are wrapped, rather than the unnecessary, perhaps dangerous "wrap every callable" behaviour freezegun uses.

**Comment by alex-verve** [comment]
@adamchainz do you need help with implementing `.tick()` method? If so I think I can help with that. Also if you have particular idea how it should be implemented feel free to instruct me :)

**Comment by adamchainz** [comment]
Help with any of it would be great! These methods should all be implementable in the python side of things so no need to dive into the C. No particular idea right now, show me what you come up with!

**Comment by adamchainz** [comment]
I've closed #14 because I don't want to add `auto_tick_seconds` until there's a request. I'm not sure of all the use cases - personally I feel it's more useful to directly control time in tests with `tick=True` / `shift()` / `move_to()`.

**Comment by alex-verve** [comment]
There is an [`ignore` argument](https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L516-L519) in `freezgun` lib which seems to be useful sometimes (in my case boto3 upload was failing due to `RequestTimeTooSkewed` error).
I'm not sure if it's possible to implement it in `time-machine` tho.

For now I'm using workaround like following:

```python
from contextlib import contextmanager
from time_machine import coordinates_stack


@contextmanager
def disable_time_machine():
    global coordinates_stack

    original_coordinates_stack = coordinates_stack.copy()
    coordinates_stack.clear()
    yield
    coordinates_stack.extend(original_coordinates_stack)
```

**Comment by adamchainz** [comment]
The only way we could implement it would be through stack inspection to find the caller, and I don't think it's worth that level of complexity.

If you need to disable time-machine for a block of code you can wrap just certain blocks of code with the context manager, or use the start/stop API. You could also possibly work around it with an inner travel() to the current time - possibly we could support `destination=time_machine.REAL_TIME` or similar to support that case.

**Comment by alex-verve** [comment]
`destination=time_machine.REAL_TIME` sounds like the optimal solution (at least in my case)

**Comment by adamchainz** [comment]
FYI you can use the `escape_hatch` API now to get the real time: https://github.com/adamchainz/time-machine#escape_hatch

**Comment by adamchainz** [comment]
Decided not to wrap non-`TestCase` classes in #187. I think that's all the features we wanted to copy.
