### ISSUE TITLE
Flag that we're time traveling, with access to true datetime

### ISSUE THREAD

**Issue by pegler** [adamchainz/time-machine#206]
### Description

In some of our integration tests we make API calls to external services. Some of these require a timestamp for use in authentication. I know that excluding some modules from time-machine isn't possible due to the implementation, but having some signal that we're time traveling would suffice, along with access to the unpatched datetime module.

**Comment by adamchainz** [comment]
You can get the real time with `_time_machine.original_now()` etc., as the replacement functions do: https://github.com/adamchainz/time-machine/blob/29a9f0aa44204c9bf236f350fdc5015fd10e8e2c/src/time_machine/__init__.py#L349-L353

And you can check if time travelling based upon whether `time_machine.coordinates_stack` is empty or not.

Can you check those works for you first?

Then we could add an official API.

**Comment by pegler** [comment]
That worked perfectly. Thanks! Having it officially supported via the API would be awesome. I can work on a PR next week.

**Comment by adamchainz** [comment]
I added `escape_hatch` and released it in 2.5.0. Try it out.
