### ISSUE TITLE
Add shift to TimeMachineFixture

### ISSUE THREAD

**Issue by henribru** [adamchainz/time-machine#247]
### Description

It would be convenient if `TimeMachineFixture` supported `shift` in addition to `move_to`. You can work around the lack of this by doing `time_machine.coordinates.shift(...)`, but it's slightly more verbose and requires you to have already called `move_to`. It also doesn't interact great with a typechecker since it will think `time_machine.coordinates` could still be `None` even if you've called `move_to`.

Would a contribution for this feature be accepted?

Edit: It would also simplify migration from pytest-freezegun since there you have both `move_to` and `tick`

**Comment by adamchainz** [comment]
Yes sure!

**Comment by AgDude** [comment]
I see similar functionality has been proposed in #38. That seems like a good way to address my concern about putting entirely new functionality into the fixture, since the fixture could simply use a zero delta to initialize the `traveller`.

**Comment by adamchainz** [comment]
@AgDude adding `timedelta()` support would be neat. Would you like to make a PR?

**Comment by soxofaan** [comment]
I created PR #312 to add `shift()` method to the pytest fixture.

It just addresses the easy part of this request: when `move_to()` has been used before.
The use case discussed by @AgDude , where `move_to()` is not called first, the implementation just raises a RunTimeError  at the moment.

**Comment by llucax** [comment]
Isn't this done?

**Comment by adamchainz** [comment]
Yup, thanks for noting.
