### ISSUE TITLE
Captain! We can't seem to lock on to the exact millisecond!

### ISSUE THREAD

**Issue by jamespacileo** [adamchainz/time-machine#248]
### Python Version

3.7

### pytest Version

7.1.2

### Package Version

2.6.0

### Description

The void of space is vast.

Only 0.0000000000000000000042% of the space is composed of matter.

"You could shoot a bullet and it would go on for millions of light years without hitting an object!" said Admiral Faustus.

"But Captain..." the Engineer awkwardly trying to find his voice.

The Admiral fiercely gripping the deck, intently observing the activity monitor. Thousands of red dots swiftly moved towards the center of the screen. The enemy was upon them.
"There's no time the Cylons are on us! We need to make the jump in time! Has the Machine made it's calculations?" 

"Yes sir" replied the Head engineer

"By the Machine's calculations will we land at the given time in empty space?"

"Yes but..." the engineer feared that the machine wasn't precise enough for such a jump, it has never been tested. Even a small miscalculation could result in catastrophe.

But the Cylons were upon them, and who was the engineer to judge the Machine that has never failed them before. The Machine has always been precise and accurate.

"Press the Machine's button" the Captain was furious

The engineer composed himself. The Machine will not fail us.
"Yes Sir" said the Head Engineer as he pressed the button.

Alas, the Machine failed them. The entirety of humanity vaporized as the intergalactic colony vessel The Hope reappeared in the core of a white dwarf. 

Even though it seems the local universe is almost static, everything is moving at almost light speed pace. The Machine knew this. The Machine was coded for this. The Machine had the computational power.
But was humanity didn't know is that the Machine had a very small error, so small, it never mattered.

The Machine teleported The Hope 1 millisecond too early, and so humanity ended in one big blast

----

I've changed my Pandas timestamps to seconds, noticed the ms part is actually based on current time.

Not sure if it's a bug. Hi @adamchainz  :)

**Comment by adamchainz** [comment]
Can you provide a reproduction?

**Comment by jamespacileo** [comment]
@adamchainz yeah I can try and sort a reproduction out, give me a bit.

Anyway, just wanted to say this library is awesome well done @adamchainz  :)

**Comment by adamchainz** [comment]
Roger that lieutenant.

**Comment by alchen** [comment]
I just run into this same problem.

```python
@time_machine.travel(datetime.datetime(2020, 1, 1, 0, 0, 0, 0));
def func(...):
  ...
  timezone.localtime().isoformat()
```

will give us this:

```
...00:00.012345+00:00
```

The microseconds seem to reflect the current time with the real clock.

**Comment by adamchainz** [comment]
I added a new note to the "Usage" section in the README that points to the migrating section.

I'm gonna close this issue for now as I'm 90% certain that it's what @jamespacileo encountered, but will reopen if there's more info.

**Comment by jamespacileo** [comment]
Hey sorry @adamchainz been hard to find the time to provide an reproducible example.

Re-opening sounds good in that case. Anyway best time-machine library there is :)
