### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by j4mie** [adamchainz/time-machine#25]
Hi,

Thanks for building this - looks very exciting and will hopefully speed up our tests a lot.

Unfortunately I can't currently get it to install (Python 3.6.2 on MacOS):

```
$ env/bin/python --version
Python 3.6.2

$ env/bin/pip install time-machine
Collecting time-machine
  Using cached time-machine-1.0.1.tar.gz (60 kB)
  WARNING: Generating metadata for package time-machine produced metadata for project name unknown. Fix your #egg=time-machine fragments.
Building wheels for collected packages: unknown, unknown
  Building wheel for unknown (setup.py) ... done
  Created wheel for unknown: filename=UNKNOWN-0.0.0-cp36-cp36m-macosx_10_15_x86_64.whl size=4748 sha256=3d9e0639969264f65a9c208b31862567bef56f493b10e88ae9e9c9110e7bad78
  Stored in directory: /Users/jamie/Library/Caches/pip/wheels/5d/7c/4c/042fbaeda0209ab73ce5a275df4efc49a2d8de09fccea3413d
  Building wheel for unknown (setup.py) ... done
  Created wheel for unknown: filename=UNKNOWN-0.0.0-cp36-cp36m-macosx_10_15_x86_64.whl size=4748 sha256=3d9e0639969264f65a9c208b31862567bef56f493b10e88ae9e9c9110e7bad78
  Stored in directory: /private/var/folders/zv/cntypnxj6pgb2tq59c9bdvd40000gn/T/pip-ephem-wheel-cache-yvxvovid/wheels/3f/9b/e7/1ab852a3e52202a96e5c9a963218743f990d693b3b9aeac5d8
Successfully built unknown unknown
Installing collected packages: unknown
Successfully installed unknown-0.0.0

$ env/bin/python -c 'import time_machine'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'time_machine'
```

**Comment by matthiask** [comment]
Did you try updating setuptools inside your virtualenv? This might help. And also pip and wheel while you're at it (`env/bin/pip install -U pip wheel setuptools`)

**Comment by jheld** [comment]
If it's a `setuptools` issue, is there a way to add an `install_requires` for the mimimal version of `setuptools`? I'm asking for curiosity as well as installation improvements.

**Comment by adamchainz** [comment]
I believe there is but I’ve never done it, and don’t know if it has caveats.

3.6.2 is also really old in that series, upgrade to 3.6.10 to ensure it’s not a python issue.

**Comment by j4mie** [comment]
Thank you, upgrading setuptools fixed it. Unfortunately we're stuck on 3.6.2 for now due to an infrastructure issue.

I am getting a load of test failures now though 😃 I'll do some digging and open another issue if I can't solve it.

Thanks again!

**Comment by adamchainz** [comment]
Great, enjoy.
