### ISSUE TITLE
Tick starts work only after time function was called

### ISSUE THREAD

**Issue by a-yangyi** [adamchainz/time-machine#263]
### Python Version

3.8

### Package Version

2.7.1

### Description

I expected tick immediately but it started only after i call a time function. When I set sleep second to 5, acted no diffrence. Is it a bug?
![image](https://user-images.githubusercontent.com/35716412/175877295-80a3386a-0a8e-4371-8f92-82aa9f62d25e.png)

Here's in freezegun:
![image](https://user-images.githubusercontent.com/35716412/175878321-1d627406-06bb-4ec4-b4af-9d3d388ac800.png)

**Comment by adamchainz** [comment]
It's not a bug, it's well documented, read the docs for `tick` again: https://github.com/adamchainz/time-machine#traveldestination--ticktrue

Also please don't paste screenshots of code on github, paste code itself, and spend some time editing to show the minimum amount to make your point. If I had to reproduce your bug, I would've needed to write out the code myself, which would be a waste of my time.
