### ISSUE TITLE
Slower unit-tests when migrating from freezegun

### ISSUE THREAD

**Issue by marcoacierno** [adamchainz/time-machine#283]
### Python Version

3.10.7-final-0

### pytest Version

7.1.3

### Package Version

2.8.1

### Description

I am testing migrating from freezegun to time-machine to gain a "free" speed improvement on our unit-tests but after updating the code the tests actually got slower from 3:54 to 4:10

The times are coming from pytest output message at the end:

```
==== 3776 passed, 2 skipped, 2 xfailed, 7815 warnings in 234.02s (0:03:54) =====

===== 3776 passed, 2 skipped, 2 xfailed, 59 warnings in 250.23s (0:04:10) ======
```

(the difference in number of warnings is interesting, but not sure if connected :))

Do you have any tips (and tools) on how I can benchmark my test suite to understand what got slower?

I tried running it to get the slowest 20 tests with/without time-machine and it is pretty much the same

**Comment by adamchainz** [comment]
Please sample a few times - benchmarking can be quite noisy and dominated by other things, like CPU speed scaling.

Also, how many of your tests use time-machine vs freezegun? If it's just a few, you won't see a huge speedup. You'd be better anyway just timing the affected tests.

**Comment by adamchainz** [comment]
Closing due to no reply. time-machine is [well-benchmarked](https://adamj.eu/tech/2021/02/19/freezegun-versus-time-machine/) as much faster, I really suspect the problem here was noise.
