### ISSUE TITLE
Add support for monotonic time

### ISSUE THREAD

**Issue by dcrowe** [adamchainz/time-machine#29]
Your library looks super cool and I'd love to use it in an upcoming project on mine, but we will also need to be able to test against the monotonic clocks as well.

I'd like to contribute the code if it is something you are would like to have in the project.

Here's my initial thoughts on what API changes might be desirable:
* add optional arguments to travel.__ini__ to accept initial values for monotonic and monotonic_raw
* add optional arguments to Coordinates.shift to allow shifting monotonic clocks by a different amount to the system clock

What do you think?

**Comment by adamchainz** [comment]
I'm not interested in adding support for monotonic clocks. I think it will complicate the library for little gain. As I understand there are three functions for accessing monotonic time: `time.monotonic()`, `time.monotonic_ns()`, and `time.clock_gettime()` with the right clock ID's. Systems probably only use one of these, so there isn't the same problem with the calendar time functions where the return values from several different functions have to be kept in-sync for a sane world. You should be able to use `unittest.mock.patch()` in your tests without much difficulty.

**Comment by dcrowe** [comment]
I can certainly understand why you wouldn't want to take the complexity into your library, but in my (almost certainly rather specialised) situation we would gain great value from being able to easily shift the monotonic clocks in tandem with the system clocks.

A simple example is a function that warns if a operation takes too long to complete and then reports an error. It would use a mono clock to measure elapsed time and then report the error in system time.

**Comment by adamchainz** [comment]
You can always wrap time-machine plus `mock.patch`

```python
from contextlib import contextmanager

@contextmanager
def clock_shifter(destination):
    with time_machine.travel(destination), mock.patch('time.monotonic', ...):
       yield
```

**Comment by asottile-sentry** [comment]
ah bummer.  this prevents us from using this in sentry.  this patch gets it working simply enough:

```diff
$ git diff
diff --git a/src/_time_machine.c b/src/_time_machine.c
index 5436e59..c5ca18f 100644
--- a/src/_time_machine.c
+++ b/src/_time_machine.c
@@ -11,6 +11,8 @@ typedef struct {
     PyCFunction original_gmtime;
     PyCFunction original_localtime;
     PyCFunction original_strftime;
+    PyCFunction original_monotonic;
+    PyCFunction original_monotonic_ns;
     PyCFunction original_time;
     PyCFunction original_time_ns;
 } _time_machine_state;
@@ -400,6 +402,16 @@ _time_machine_patch_if_needed(PyObject *module, PyObject *unused)
     time_strftime->m_ml->ml_meth = _time_machine_strftime;
     Py_DECREF(time_strftime);
 
+    PyCFunctionObject *time_monotonic = (PyCFunctionObject *) PyObject_GetAttrString(time_module, "monotonic");
+    state->original_monotonic = time_monotonic->m_ml->ml_meth;
+    time_monotonic->m_ml->ml_meth = _time_machine_time;
+    Py_DECREF(time_monotonic);
+
+    PyCFunctionObject *time_monotonic_ns = (PyCFunctionObject *) PyObject_GetAttrString(time_module, "monotonic_ns");
+    state->original_monotonic_ns = time_monotonic_ns->m_ml->ml_meth;
+    time_monotonic_ns->m_ml->ml_meth = _time_machine_time_ns;
+    Py_DECREF(time_monotonic_ns);
+
     PyCFunctionObject *time_time = (PyCFunctionObject *) PyObject_GetAttrString(time_module, "time");
     state->original_time = time_time->m_ml->ml_meth;
     time_time->m_ml->ml_meth = _time_machine_time;
```

but doesn't give you full freedom to control a monotonic vs non-monotonic clock separately -- which I think for _most_ usecases is probably fine?

**Comment by adamchainz** [comment]
Okay if it’s still coming up, let’s add it. Would you like to open a PR @asottile-sentry ?
