### ISSUE TITLE
inexact results with pandas

### ISSUE THREAD

**Issue by wimglenn** [adamchainz/time-machine#293]
### Python Version

3.10.6

### pytest Version

-

### Package Version

2.8.2

### Description

```
>>> with time_machine.travel("2000-01-01 00:12:34.567890"):
...     print(datetime.now())
...     print(pd.Timestamp("now"))
...     print(pd.Timestamp.now())
...     print(pd.to_datetime("now", utc=True))
...     print(np.datetime64("now"))
... 
2000-01-01 00:12:34.567890
2000-01-01 00:12:34.567942
2000-01-01 00:12:34.567986
2000-01-01 06:12:34.568156+00:00
2022-10-20T02:25:38
```

The result with stdlib datetime is exact, but the results with pandas suffer a kind of delay or something(?)
Also it looks like numpy was not affected at all.

pandas v1.5.1 and numpy v1.23.4 on macOS

**Comment by adamchainz** [comment]
This is the `tick` flag defaulting to `True`, time advances after the first call to a clock. Put `pd.Timestamp("now")` first and you'll see the exact time. Refer to the docs for more info.

**Comment by adamchainz** [comment]
Can you make a separate issue for numpy so I can look into it? Likely it reads the clock directly... *maybe* we can mock that as well, but no guarantees.
