### ISSUE TITLE
Flaky time-related test in downstream 'tox' project unit test

### ISSUE THREAD

**Issue by jayaddison** [adamchainz/time-machine#311]
### Python Version

cpython 3.11

### pytest Version

7.2.0

### Package Version

2.8.2

### Description

[This unit test](https://github.com/tox-dev/tox/blob/0edd3a4967c4cfaa640d3f4eb75bec0c6d19dd06/tests/util/test_spinner.py#L74-L95) in (downstream `time-machine` usage-site) `tox` [includes a representation of elapsed time](https://github.com/tox-dev/tox/blob/0edd3a4967c4cfaa640d3f4eb75bec0c6d19dd06/src/tox/execute/api.py#L240) is [evidently](https://github.com/tox-dev/tox/pull/2731/files#diff-3df1ee91a3ba1628688e5eb137ddb02aeb8c7da19cd150607a37de0c0478dbd6R75) experiencing [flaky results](https://github.com/tox-dev/tox/actions/runs/3707269841/jobs/6283484233#step:8:152) for some reason.

Please note: I'm not certain that `time-machine` is the cause here; it seems possible-to-likely to me though - I'm continuing to investigate.

The above failure was on Windows 2022, and I'll try to determine whether that platform is a shared trait among the failing tests, or not a relevant factor.

**Comment by jayaddison** [comment]
Another build log exhibiting a time-related failure in the same unit test -- also Windows 2022 -- https://github.com/tox-dev/tox/actions/runs/3649639395/jobs/6164575909#step:8:139

**Comment by jayaddison** [comment]
Potentially related to #29; elapsed time is being calculated based on two `time.monotonic()` calls ([`start`](https://github.com/tox-dev/tox/blob/0edd3a4967c4cfaa640d3f4eb75bec0c6d19dd06/src/tox/execute/api.py#L119), [`end`](https://github.com/tox-dev/tox/blob/0edd3a4967c4cfaa640d3f4eb75bec0c6d19dd06/src/tox/execute/api.py#L131)).

**Comment by adamchainz** [comment]
I don't think time-machine is the cause here. time-machine doesn't mock time.monotonic; previously the idea to add it was also open in #103 but closed because it's orthogonal, and not many people need it. You can mock.patch time.monotonic in tests that need it. I think that should work for that test in tox.
