### ISSUE TITLE
`time.monotonic()` support.

### ISSUE THREAD

**Issue by GoodWasHere** [adamchainz/time-machine#369]
### Description

Hello.
Thanks for the great project.
Is there any possibility to add mocking of `time.monotonic` and `time.monotonic_ns` functions from stanart library?
They are often used and at the moment the time machine does not affect their behavior.

**Comment by adamchainz** [comment]
Decided against in #29 and https://github.com/adamchainz/time-machine/pull/104#issuecomment-1232276789 . Please search project issue trackers before opening issues.

**Comment by GoodWasHere** [comment]
Adding `monotonic` support would allow to use `time-machine` as a universal tool, without having to examine the code of third-party modules to find out what timing functions they use (or don't use) under the hood.

Thanks anyway.
