### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [adamchainz/time-machine#378]
### Description

Is it possible next time on release new version make the github release to have entry on https://github.com/adamchainz/time-machine/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.
My automation process those notification trying make preliminary automated upgrade of building packages which allow save some time on maintaining packaging procedures.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by adamchainz** [comment]
I’d rather not maitain another thing for every release (of every project I maintain, I want consistency). Subscribe to the PyPI releases RSS feed: https://pypi.org/project/time-machine/#history .

**Comment by kloczek** [comment]
Your repo already is using GH workflows so you don't need to maintain anything on every release.
Please have look on https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026

**Comment by adamchainz** [comment]
If I start doing them, I can never stop. I’d rather not commit.

**Comment by kloczek** [comment]
> If I start doing them, I can never stop. I’d rather not commit.

All what you need to do is do one time change in workflows.
HG release can be without any additional comments (empty one) because subject of the email notariatom contains core of the notyfication.
