### ISSUE TITLE
Adding support for tzlocal

### ISSUE THREAD

**Issue by hmaarrfk** [adamchainz/time-machine#418]
### Python Version

3.10.12

### pytest Version

7.4.3

### Package Version

2.13.0

### Description

```
import tzlocal
from zoneinfo import ZoneInfo
import time_machine
from datetime import datetime


print(tzlocal.get_localzone_name())


with time_machine.travel(datetime(
        year=2023, month=3, day=4,
        hour=11, minute=5, second=6, microsecond=987,
        tzinfo=ZoneInfo("Pacific/Pohnpei"))
):
    print(tzlocal.get_localzone_name())

with time_machine.travel(datetime(
        year=2023, month=3, day=4,
        hour=11, minute=5, second=6, microsecond=987,
        tzinfo=ZoneInfo("Pacific/Pohnpei"))
):
    tzlocal.reload_localzone()
    print(tzlocal.get_localzone_name())
```

**Comment by hmaarrfk** [comment]
Sorry my message didn't fully get typed up,

I'm not sure how much you want to support tzlocal, but hopefully this example shows how to in the context manager.

**Comment by hmaarrfk** [comment]
And reference to tzlocal's code:
https://github.com/regebro/tzlocal/blob/master/tzlocal/unix.py#L224C5-L224C21

**Comment by adamchainz** [comment]
I don't want to support anything but Python’s standard library. You can write a `time_machine.travel()` wrapper that calls `reload_localzone` when starting and stopping.

**Comment by hmaarrfk** [comment]
understood. thats what i did in my test suite. thanks!
