### ISSUE TITLE
Support new PyTime C API

### ISSUE THREAD

**Issue by ariebovenberg** [adamchainz/time-machine#464]
### Description

Python 3.13 will include a new C API for the `time` library: https://docs.python.org/3.13/c-api/time.html. Would `time-machine` be able to support patching it as well?

Considering it consists of static types and functions, I'm unsure if it can even be patched 👀 

edit: typo

**Comment by adamchainz** [comment]
Yeah, I don't think it can be patched, as nice as that would be.

**Comment by ariebovenberg** [comment]
@adamchainz I'm C-beginner here, but: would it be possible for `time-machine` to provide a function pointer that points to `PyTime_Time` and switches to a patched version when time_machine is travelling? That way, a C extension could easily opt-in to time-machine support 🤔

**Comment by adamchainz** [comment]
It may be possible with some hacks, but they may need to be OS and architecture-specific, and need to circumvent some memory protection. More than I know how to do or am willing to try and maintain.
