### ISSUE TITLE
travel tz_offset is incompatible to libfaketime/freezegun

### ISSUE THREAD

**Issue by danygielow** [adamchainz/time-machine#75]
Hi,

The usage of tz_offset is incompatible to libfaketime and freeezegun.
time-machine uses the tz_offset for UTC and local time. libfaketime and freezegun use it only for the local time and the given date target is used as the UTC time.

see the following tests:
https://github.com/simon-weber/python-libfaketime/blob/master/test/test_faketime.py#L53
https://github.com/spulec/freezegun/blob/master/tests/test_datetimes.py#L77

I already opened an incomplete PR #65. But I am hopeless when it comes to timezones and C code. So I am hoping for a contributor, that can fix this incompatiblity.

Affected version: <=1.2.0

Thanks

**Comment by adamchainz** [comment]
Hi @danygielow 

Since you've opened a PR already, let's keep the conversation there, in one place.
